#!/usr/bin/env sh

alias \
yarn="yarn --use-yarnrc \"$XDG_CONFIG_HOME/yarn/config\"" \
conky="conky --config=\"$XDG_CONFIG_HOME/conky/conkyrc\"" \
zshrc="$EDITOR $XDG_CONFIG_HOME/zsh/.zshrc" \
conky-reload="killall -SIGUSR1 conky" \
sxhkd-reload="killall -SIGUSR1 sxhkd" \
waybar-reload="killall -SIGUSR2 waybar" \

alias \
0="clear" \
g="git" \
v="$EDITOR" \
mkd="mkdir -pv" \
rmd="rm -r" \
sln="ln -s" \
ls="ls -pt --color=always --group-directories-first" \
ll="ls -AhlX --color=always --group-directories-first" \
lt="ls -RU --color=always --group-directories-first" \
lsbc="lsblk | bat -p -l conf" \
qrshow="qrencode -o - -t UTF8" \
mpva="mpv --no-video" \
copy="dmenu-cb" \

alias -g \
G="| grep" \
L="| less" \
E="| nvim -" \
