#!/usr/bin/env sh

alias \
yarn="yarn --use-yarnrc \"$XDG_CONFIG_HOME/yarn/config\"" \
conky="conky --config=\"$XDG_CONFIG_HOME/conky/conkyrc\"" \
zshrc="$EDITOR $XDG_CONFIG_HOME/zsh/.zshrc" \
conky-reload="killall -SIGUSR1 conky" \
sxhkd-reload="killall -SIGUSR1 sxhkd" \
waybar-reload="killall -SIGUSR2 waybar" \
#: gnu
alias \
0="clear" \
g="git" \
v="$EDITOR" \
mkd="mkdir -pv" \
rmd="rm -r" \
sln="ln -s" \
lsbc="lsblk | bat -p -l conf" \
ls="ls -pt --color=always" \
ll="ls -AhlX --color=always" \
lt="ls -RU --color=always" \
#: pipes
alias -g \
G="| grep" \
L="| less" \
E="| nvim -" \

jq-format() {
    jq '.' $1 | sponge $1
}
