#!/usr/bin/env sh

alias \
yarn="yarn --use-yarnrc \"$XDG_CONFIG_HOME/yarn/config\"" \
waybar-reload="killall -SIGUSR2 waybar" \
wget="wget --hsts-file=$XDG_STATE_HOME/wget-hsts" \

#: gnu
alias \
0="clear" \
g="git" \
v="$EDITOR" \
mkd="mkdir -pv" \
rmd="rm -r" \
sln="ln -s" \
lsbc="lsblk | bat -p -l conf" \
ls="ls -pt --color=always" \
ll="ls -AhlX --color=always" \
lt="ls -RU --color=always" \
#: pipes
alias -g \
A="| awk" \
E="| nvim -" \
G="| grep" \
L="| less" \

command -v "soffice" >/dev/null && alias doc2pdf="soffice --convert-to pdf"
#: linux only
command -v "xdg-open" >/dev/null && alias open="setsid xdg-open"
command -v "dragon-drop" >/dev/null && alias drag="dragon-drop -x"

json-format() {
    jq '.' $1 | sponge $1
}
