#!/usr/bin/env bash

STATUS=$(playerctl status 2>/dev/null)
EXIT_CODE=$?

if [[ $EXIT_CODE -eq 0 ]]; then
	echo "$STATUS"
else
	echo "No player"
fi

case $BUTTON in 
	1) notify-send "$BLOCK_BUTTON" ;;
	3) notify-send "$BLOCK_BUTTON" ;;
	6) notify-send "$BLOCK_BUTTON" ;;
esac
