#!/usr/bin/env sh

p=~/Projects
dots=~/dotfiles
docs=~/Documents
pics=~/Pictures
: ~p ~dots ~docs ~pics

alias \
yarn="yarn --use-yarnrc \"$XDG_CONFIG_HOME/yarn/config\"" \
conky="conky --config=\"$XDG_CONFIG_HOME/conky/conkyrc\"" \
fastfetch="fastfetch --config ~dots/scripts/fastfetch.json" \

alias \
0="clear" \
d="dirs -v" \
e="$EDITOR" \
v="$EDITOR" \
mkd="mkdir -pv" \
rmd="rm -r" \
sln="ln -s" \
grep="grep --color=auto" \
cb="dmenu-cb" \
df="df -h" \
du="du -h -d 1" \
l="eza -l --no-user --color=always --icons=always" \
ll="eza -lh --color=always --group-directories-first" \
lt="eza -Rh --color=always --group-directories-first" \
ltt="eza -laR --color=always --group-directories-first" \
la="eza -lah --no-user --color=always --group-directories-first" \
zshrc="nvim $XDG_CONFIG_HOME/zsh/.zshrc" \
conky-reload="killall -SIGUSR1 conky" \
sxhkd-reload="killall -SIGUSR1 sxhkd" \
screen-half="xrandr --output HDMI-0 --brightness 0.5" \
screen-full="xrandr --output HDMI-0 --brightness 1.0" \

for n in {1..9}; do 
    alias $n="cd -$n";
done
