#!/bin/sh

alias \
yarn="yarn --use-yarnrc \"$XDG_CONFIG_HOME/yarn/config\"" \
conky="conky --config=\"$XDG_CONFIG_HOME/conky/conkyrc\"" \
fastfetch="fastfetch --config=\"~/dotfiles/ref/fastfetch.json\"" \

alias \
0="clear" \
d="dirs -v" \
dotf="cd ~/dotfiles" \
p="cd ~/Projects" \
v="$EDITOR" \
mkd="mkdir -pv" \
rmd="rm -r" \
sln="ln -s" \
grep="grep --color=auto" \
l="eza --color=always" \
ll="eza --color=always --icons=always -lh --no-user" \
lh="eza --color=always -lah --no-user" \
df="df -h" \
du="du -h -d 1" \
zshrc="nvim $XDG_CONFIG_HOME/zsh/.zshrc" \
conky-reload="killall -SIGUSR1 conky" \
sxhkd-reload="killall -SIGUSR1 sxhkd" \
screen-half="xrandr --output HDMI-0 --brightness 0.5" \
screen-full="xrandr --output HDMI-0 --brightness 1.0" \

for n in {1..9}; do 
    alias $n="cd -$n";
done
