#!/usr/bin/env bash

get_memory(){
    free --mebi | sed -n '2{p;q}' | awk '{printf ("%2.2fGiB/%2.2fGiB\n", ( $3 / 1024), ($2 / 1024))}'
}

get_memory

case $BLOCK_BUTTON in 
	1) setsid -f "$TERMINAL -e btop" ;
    pkill -RTMIN+3 dwmblocks ;;
	6) notify-send "$BLOCK_BUTTON" ;;
esac
