#!/usr/bin/env bash
# In order to use it you have to source it inside your shell config file
# Dmenu script that maps a freqently used directories provided in a file
FILE="$HOME/dotfiles/scripts/dmenu-places.store"

places_get_where () {
    where=$(cat "$FILE" | dmenu -c -l 5 -p "Places")
    echo $where
}

places () {
    place="$HOME/$(places_get_where)"
    cd $place
}
