#!/usr/bin/env bash

# original from github: BreadOnPenguins/scripts
# released under GPL-3.0 License 

case "$(printf "kill\nsuspend\nreboot\nshutdown" | dmenu -i -c -l 4)" in
	kill) ps -u $USER -o pid,comm,%cpu,%mem | dmenu -i -c -l 10 -p "Kill pid:" | awk '{print $1}' | xargs -r kill ;;
	suspend) systemctl suspend -i ;;
	reboot) systemctl reboot -i ;;
	shutdown) poweroff ;;
	*) exit 1 ;;
esac
