### WINDOWS AND WORKSPACES ###
# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more

# workspace = 4, layout:scrolling

# Scratchpad (not floating)
workspace = special:magic, float:true, on-created-empty:foot, gapsout:120
# windowrule = match:workspace special:magic, match:class foot, float on, size (monitor_w*0.6) (monitor_h*0.6)

# Popup follow
windowrule = match:class dragon-drop, pin on

# Smart gaps - for the only tiled
# workspace = w[tv1]s[false], gapsout:0, gapsin:0
# windowrule = border_size 0, match:float 0, match:workspace w[tv1]s[false]
# windowrule = rounding 0, match:float 0, match:workspace w[tv1]s[false]
# Smart gaps - for the only maximized
# workspace = f[1]s[false], gapsout:0, gapsin:0
# windowrule = border_size 0, match:float 0, match:workspace f[1]s[false]
# windowrule = rounding 0, match:float 0, match:workspace f[1]s[false]

# Full screen inhibit idle
windowrule = idle_inhibit fullscreen, match:class *

windowrule {
  name = "floats"
  match:class = pavucontrol
  match:class = io.ente.auth
  match:class = xdg-desktop-portal.*
  # match app-id=r#"firefox$"# title="^Picture-in-Picture$"

  float = on
}

# Dim - zen
windowrule = opacity 0.6, match:tag dimmer
windowrule = match:class (pinentry-)(.*), stay_focused on
