# man 5 alacritty
[general]
import = ["~/.cache/wal/colors-alacritty.toml"]

[font]
normal = { family = "Fira Code", style = "Regular" }
italic = { family = "JetBrains Mono", style = "Italic" }
size = 11.5

[cursor]
unfocused_hollow = true
style.blinking = "On"

[selection]
save_to_clipboard = true

[window]
dynamic_padding = false
opacity = 0.9
decorations = "None" # "Full"

[window.padding]
x = 14
y = 7

[mouse]
hide_when_typing = true

[scrolling]
multiplier = 10
